# Generated by Django 6.0.7 on 2026-08-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agreement_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='telephone',
        ),
    ]
