# Generated by Django 6.0.7 on 2026-08-06 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_phone_user_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agreement', to='api.agreement'),
        ),
    ]
