# Generated by Django 6.0.7 on 2026-08-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_payments_agreement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
